# Generated by Django 4.2.26 on 2025-11-19 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccommodationUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('type', models.CharField(choices=[('CHALET', 'Chalet'), ('SUITE', 'Suite'), ('ROOM', 'Room'), ('APARTMENT', 'Apartment')], default='CHALET', max_length=20, verbose_name='Type')),
                ('max_capacity', models.PositiveIntegerField(help_text='Maximum number of guests', verbose_name='Max Capacity')),
                ('base_price', models.DecimalField(decimal_places=2, help_text='Base daily rate in Brazilian Reais', max_digits=10, verbose_name='Base Price (BRL)')),
                ('color_hex', models.CharField(default='#4A90E2', help_text='Hex color code for calendar display (e.g., #FF5733)', max_length=7, verbose_name='Calendar Color')),
                ('status', models.CharField(choices=[('CLEAN', 'Clean'), ('DIRTY', 'Dirty'), ('INSPECTING', 'Inspecting')], default='CLEAN', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Accommodation Unit',
                'verbose_name_plural': 'Accommodation Units',
                'ordering': ['name'],
            },
        ),
    ]
