# Generated by Django 4.2.26 on 2025-11-20 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodationunit',
            name='auto_dirty_days',
            field=models.PositiveIntegerField(default=3, help_text='Number of days after which a clean unit automatically becomes dirty', verbose_name='Auto Dirty Days'),
        ),
        migrations.AddField(
            model_name='accommodationunit',
            name='last_cleaned_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of when the unit was last cleaned', null=True, verbose_name='Last Cleaned At'),
        ),
    ]
