# Generated by Django 4.2.27 on 2025-12-15 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodations', '0002_accommodationunit_auto_dirty_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodationunit',
            name='default_check_in_time',
            field=models.TimeField(default='14:00', help_text='Default check-in time for this unit (e.g., 14:00)', verbose_name='Default Check-in Time'),
        ),
        migrations.AddField(
            model_name='accommodationunit',
            name='default_check_out_time',
            field=models.TimeField(default='12:00', help_text='Default check-out time for this unit (e.g., 12:00)', verbose_name='Default Check-out Time'),
        ),
    ]
