# Generated by Django 4.2.27 on 2025-12-15 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodations', '0003_add_default_check_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodationunit',
            name='holiday_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Daily rate for holidays in Brazilian Reais', max_digits=10, null=True, verbose_name='Holiday Price (BRL)'),
        ),
        migrations.AddField(
            model_name='accommodationunit',
            name='weekend_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Daily rate for weekends (Fri, Sat, Sun) in Brazilian Reais', max_digits=10, null=True, verbose_name='Weekend Price (BRL)'),
        ),
    ]
