# Generated by Django 4.2.27 on 2025-12-16 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accommodations', '0004_add_weekend_holiday_prices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accommodationunit',
            name='type',
        ),
    ]
