# Generated by Django 4.2.27 on 2025-12-22 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodations', '0005_remove_type_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accommodationunit',
            options={'ordering': ['display_order', 'name'], 'verbose_name': 'Unidade de Acomodação', 'verbose_name_plural': 'Unidades de Acomodação'},
        ),
        migrations.AddField(
            model_name='accommodationunit',
            name='display_order',
            field=models.IntegerField(default=0, help_text='Ordem em que a unidade aparece na lista e no calendário (menor = primeiro)', verbose_name='Ordem de Exibição'),
        ),
        migrations.AlterField(
            model_name='accommodationunit',
            name='auto_dirty_days',
            field=models.PositiveIntegerField(default=3, help_text='Número de dias após os quais uma unidade limpa automaticamente fica suja', verbose_name='Dias Auto-Sujo'),
        ),
        migrations.AlterField(
            model_name='accommodationunit',
            name='base_price',
            field=models.DecimalField(decimal_places=2, help_text='Diária base em Reais', max_digits=10, verbose_name='Preço Base (BRL)'),
        ),
        migrations.AlterField(
            model_name='accommodationunit',
            name='color_hex',
            field=models.CharField(default='#4A90E2', help_text='Código de cor hex para exibição no calendário (ex: #FF5733)', max_length=7, verbose_name='Cor do Calendário'),
        ),
        migrations.AlterField(
            model_name='accommodationunit',
            name='default_check_in_time',
            field=models.TimeField(default='14:00', help_text='Horário padrão de check-in para esta unidade (ex: 14:00)', verbose_name='Horário Padrão de Check-in'),
        ),
        migrations.AlterField(
            model_name='accommodationunit',
            name='default_check_out_time',
            field=models.TimeField(default='12:00', help_text='Horário padrão de check-out para esta unidade (ex: 12:00)', verbose_name='Horário Padrão de Check-out'),
        ),
        migrations.AlterField(
            model_name='accommodationunit',
            name='holiday_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Diária para feriados em Reais', max_digits=10, null=True, verbose_name='Preço Feriado (BRL)'),
        ),
        migrations.AlterField(
            model_name='accommodationunit',
            name='last_cleaned_at',
            field=models.DateTimeField(blank=True, help_text='Data e hora em que a unidade foi limpa pela última vez', null=True, verbose_name='Última Limpeza'),
        ),
        migrations.AlterField(
            model_name='accommodationunit',
            name='max_capacity',
            field=models.PositiveIntegerField(help_text='Número máximo de hóspedes', verbose_name='Capacidade Máxima'),
        ),
        migrations.AlterField(
            model_name='accommodationunit',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='accommodationunit',
            name='status',
            field=models.CharField(choices=[('CLEAN', 'Limpo'), ('DIRTY', 'Sujo'), ('INSPECTING', 'Inspecionando')], default='CLEAN', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='accommodationunit',
            name='weekend_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Diária para finais de semana (Sex, Sáb, Dom) em Reais', max_digits=10, null=True, verbose_name='Preço Final de Semana (BRL)'),
        ),
    ]
