# Generated by Django 4.2.27 on 2025-12-22 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accommodations', '0006_alter_accommodationunit_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatePriceOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Data específica para aplicar o preço customizado', verbose_name='Data')),
                ('price', models.DecimalField(decimal_places=2, help_text='Preço customizado para esta data', max_digits=10, verbose_name='Preço (BRL)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accommodation_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date_price_overrides', to='accommodations.accommodationunit', verbose_name='Unidade de Acomodação')),
            ],
            options={
                'verbose_name': 'Preço Customizado por Data',
                'verbose_name_plural': 'Preços Customizados por Data',
                'ordering': ['date', 'accommodation_unit'],
                'indexes': [models.Index(fields=['accommodation_unit', 'date'], name='accommodati_accommo_50cdcd_idx'), models.Index(fields=['date'], name='accommodati_date_ceb35f_idx')],
                'unique_together': {('accommodation_unit', 'date')},
            },
        ),
        migrations.CreateModel(
            name='DatePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome descritivo do pacote (ex: Natal 2025, Carnaval)', max_length=100, verbose_name='Nome do Pacote')),
                ('start_date', models.DateField(verbose_name='Data Inicial')),
                ('end_date', models.DateField(verbose_name='Data Final')),
                ('color', models.CharField(default='#4A90E2', help_text='Código de cor hex para exibição no calendário (ex: #FF5733)', max_length=7, verbose_name='Cor')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accommodation_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date_packages', to='accommodations.accommodationunit', verbose_name='Unidade de Acomodação')),
            ],
            options={
                'verbose_name': 'Pacote de Datas',
                'verbose_name_plural': 'Pacotes de Datas',
                'ordering': ['-created_at', 'start_date', 'accommodation_unit'],
                'indexes': [models.Index(fields=['accommodation_unit', 'start_date', 'end_date'], name='accommodati_accommo_b9533c_idx'), models.Index(fields=['start_date', 'end_date'], name='accommodati_start_d_11e48d_idx')],
            },
        ),
    ]
