# Generated by Django 4.2.27 on 2026-01-04 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodations', '0007_datepriceoverride_datepackage'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodationunit',
            name='album_photos',
            field=models.JSONField(blank=True, default=list, help_text='Lista de URLs de fotos da unidade', verbose_name='Álbum de Fotos'),
        ),
        migrations.AddField(
            model_name='accommodationunit',
            name='long_description',
            field=models.TextField(blank=True, default='', help_text='Descrição completa da unidade (formato markdown)', verbose_name='Descrição Longa'),
        ),
        migrations.AddField(
            model_name='accommodationunit',
            name='rules',
            field=models.TextField(blank=True, default='', help_text='Regras da unidade (formato markdown)', verbose_name='Regras'),
        ),
        migrations.AddField(
            model_name='accommodationunit',
            name='short_description',
            field=models.TextField(blank=True, default='', help_text='Breve descrição da unidade (formato markdown)', verbose_name='Descrição Curta'),
        ),
    ]
