# Generated by Django 4.2.27 on 2026-01-04 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodations', '0007_datepriceoverride_datepackage'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodationunit',
            name='album_photos',
            field=models.JSONField(blank=True, default=list, help_text='Lista de URLs das fotos da unidade', verbose_name='Álbum de Fotos'),
        ),
        migrations.AddField(
            model_name='accommodationunit',
            name='long_description',
            field=models.TextField(blank=True, help_text='Descrição detalhada da unidade (suporta markdown)', null=True, verbose_name='Descrição Longa'),
        ),
        migrations.AddField(
            model_name='accommodationunit',
            name='rules',
            field=models.TextField(blank=True, help_text='Regras e normas da unidade (suporta markdown)', null=True, verbose_name='Regras da Acomodação'),
        ),
        migrations.AddField(
            model_name='accommodationunit',
            name='short_description',
            field=models.TextField(blank=True, help_text='Breve descrição da unidade (suporta markdown)', null=True, verbose_name='Descrição Curta'),
        ),
    ]
