# Generated by Django 4.2.27 on 2026-01-07 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodations', '0008_accommodationunit_album_photos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodationunit',
            name='location',
            field=models.CharField(blank=True, default='', help_text='Endereço ou coordenadas da unidade para exibição no Google Maps', max_length=500, verbose_name='Localização'),
        ),
    ]
