# Generated by Django 4.2.27 on 2026-01-07 20:30

import accommodations.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accommodations', '0008_accommodationunit_album_photos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Imagem da unidade', upload_to=accommodations.models.unit_image_upload_path, verbose_name='Imagem')),
                ('order', models.PositiveIntegerField(default=0, help_text='Ordem de exibição da imagem', verbose_name='Ordem')),
                ('caption', models.CharField(blank=True, default='', help_text='Legenda opcional da imagem', max_length=200, verbose_name='Legenda')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accommodation_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='accommodations.accommodationunit', verbose_name='Unidade de Acomodação')),
            ],
            options={
                'verbose_name': 'Imagem da Unidade',
                'verbose_name_plural': 'Imagens das Unidades',
                'ordering': ['accommodation_unit', 'order', 'id'],
                'indexes': [models.Index(fields=['accommodation_unit', 'order'], name='accommodati_accommo_5f0288_idx')],
            },
        ),
    ]
