# Generated by Django 4.2.27 on 2025-12-22 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accommodations', '0006_alter_accommodationunit_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Nome do Pacote')),
                ('description', models.TextField(blank=True, help_text='Descrição detalhada do pacote', verbose_name='Descrição')),
                ('package_price', models.DecimalField(decimal_places=2, help_text='Preço total do pacote em Reais', max_digits=10, verbose_name='Preço do Pacote (BRL)')),
                ('is_active', models.BooleanField(default=True, help_text='Pacote disponível para reserva', verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accommodation_units', models.ManyToManyField(help_text='Unidades incluídas neste pacote', related_name='packages', to='accommodations.accommodationunit', verbose_name='Unidades de Acomodação')),
            ],
            options={
                'verbose_name': 'Pacote',
                'verbose_name_plural': 'Pacotes',
                'ordering': ['name'],
            },
        ),
    ]
