# Generated by Django 4.2.26 on 2025-11-19 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount in Brazilian Reais', max_digits=10, verbose_name='Amount (BRL)')),
                ('transaction_type', models.CharField(choices=[('INCOME', 'Income (Account Receivable)'), ('EXPENSE', 'Expense (Account Payable)')], max_length=20, verbose_name='Transaction Type')),
                ('category', models.CharField(choices=[('LODGING', 'Lodging'), ('MAINTENANCE', 'Maintenance'), ('UTILITIES', 'Utilities'), ('SUPPLIES', 'Supplies'), ('SALARY', 'Salary'), ('OTHER', 'Other')], default='LODGING', max_length=20, verbose_name='Category')),
                ('payment_method', models.CharField(choices=[('PIX', 'Pix'), ('CREDIT_CARD', 'Credit Card'), ('DEBIT_CARD', 'Debit Card'), ('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer')], max_length=20, verbose_name='Payment Method')),
                ('due_date', models.DateField(verbose_name='Due Date')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='Paid Date')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='reservations.reservation', verbose_name='Reservation')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-due_date'],
            },
        ),
    ]
