# Generated by Django 4.2.26 on 2025-12-22 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_add_payment_pool'),
        ('financials', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-due_date'], 'verbose_name': 'Transação', 'verbose_name_plural': 'Transações'},
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Valor em Reais', max_digits=10, verbose_name='Valor (BRL)'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('LODGING', 'Hospedagem'), ('MAINTENANCE', 'Manutenção'), ('UTILITIES', 'Utilidades'), ('SUPPLIES', 'Suprimentos'), ('SALARY', 'Salário'), ('OTHER', 'Outro')], default='LODGING', max_length=20, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='due_date',
            field=models.DateField(verbose_name='Data de Vencimento'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='paid_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Pagamento'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[('PIX', 'Pix'), ('CREDIT_CARD', 'Cartão de Crédito'), ('DEBIT_CARD', 'Cartão de Débito'), ('CASH', 'Dinheiro'), ('BANK_TRANSFER', 'Transferência Bancária')], max_length=20, verbose_name='Método de Pagamento'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='reservations.reservation', verbose_name='Reserva'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('INCOME', 'Receita (Contas a Receber)'), ('EXPENSE', 'Despesa (Contas a Pagar)')], max_length=20, verbose_name='Tipo de Transação'),
        ),
    ]
