# Generated by Django 4.2.26 on 2025-11-19 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accommodations', '0001_initial'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateTimeField(verbose_name='Check-in Date/Time')),
                ('check_out', models.DateTimeField(verbose_name='Check-out Date/Time')),
                ('guest_count_adults', models.PositiveIntegerField(default=1, verbose_name='Adult Guests')),
                ('guest_count_children', models.PositiveIntegerField(default=0, verbose_name='Children Guests')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CHECKED_IN', 'Checked-in'), ('CHECKED_OUT', 'Checked-out'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accommodation_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='accommodations.accommodationunit', verbose_name='Accommodation Unit')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='clients.client', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Reservation',
                'verbose_name_plural': 'Reservations',
                'ordering': ['-check_in'],
            },
        ),
    ]
