# Generated by Django 4.2.26 on 2025-11-20 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Manual price override. If not set, will be calculated automatically.', max_digits=10, null=True, verbose_name='Total Price (BRL)'),
        ),
    ]
