# Generated by Django 4.2.26 on 2025-11-20 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_reservation_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='price_breakdown',
            field=models.JSONField(blank=True, default=list, help_text="List of price items: [{'name': 'Diária', 'value': 100.00}, ...]", verbose_name='Price Breakdown'),
        ),
    ]
