# Generated by Django 4.2.27 on 2025-12-15 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_reservation_price_breakdown'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total amount already paid by the client', max_digits=10, verbose_name='Amount Paid (BRL)'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='payment_history',
            field=models.JSONField(blank=True, default=list, help_text="List of payment entries: [{'date': '...', 'amount': ..., 'method': '...'}, ...]", verbose_name='Payment History'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='price_breakdown',
            field=models.JSONField(blank=True, default=list, help_text="List of price items: [{'name': 'Diária', 'value': 100.00, 'quantity': 1}, ...]", verbose_name='Price Breakdown'),
        ),
    ]
