# Generated by Django 4.2.26 on 2025-12-22 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accommodations', '0006_alter_accommodationunit_options_and_more'),
        ('clients', '0006_alter_client_options_and_more'),
        ('reservations', '0004_add_payment_pool'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-check_in'], 'verbose_name': 'Reserva', 'verbose_name_plural': 'Reservas'},
        ),
        migrations.AlterField(
            model_name='reservation',
            name='accommodation_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='accommodations.accommodationunit', verbose_name='Unidade de Acomodação'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valor total já pago pelo cliente', max_digits=10, verbose_name='Valor Pago (BRL)'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='check_in',
            field=models.DateTimeField(verbose_name='Data/Hora de Check-in'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='check_out',
            field=models.DateTimeField(verbose_name='Data/Hora de Check-out'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='clients.client', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='guest_count_adults',
            field=models.PositiveIntegerField(default=1, verbose_name='Hóspedes Adultos'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='guest_count_children',
            field=models.PositiveIntegerField(default=0, verbose_name='Hóspedes Crianças'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='payment_history',
            field=models.JSONField(blank=True, default=list, help_text="Lista de entradas de pagamento: [{'date': '...', 'amount': ..., 'method': '...'}, ...]", verbose_name='Histórico de Pagamento'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='price_breakdown',
            field=models.JSONField(blank=True, default=list, help_text="Lista de itens de preço: [{'name': 'Diária', 'value': 100.00, 'quantity': 1}, ...]", verbose_name='Detalhamento de Preço'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendente'), ('CONFIRMED', 'Confirmado'), ('CHECKED_IN', 'Check-in Feito'), ('CHECKED_OUT', 'Check-out Feito'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Substituição manual de preço. Se não definido, será calculado automaticamente.', max_digits=10, null=True, verbose_name='Preço Total (BRL)'),
        ),
    ]
