# Generated by Django 4.2.27 on 2026-01-04 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_alter_reservation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='pet_count',
            field=models.PositiveIntegerField(default=0, help_text='Número de animais de estimação', verbose_name='Quantidade de Animais'),
        ),
    ]
