# Generated by Django 4.2.26 on 2025-11-19 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Full Name')),
                ('cpf', models.CharField(help_text='Format: XXX.XXX.XXX-XX', max_length=14, unique=True, verbose_name='CPF')),
                ('phone', models.CharField(help_text='Format: +55 (XX) XXXXX-XXXX', max_length=20, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('tags', models.JSONField(blank=True, default=list, help_text="List of tags like 'VIP', 'Frequent Guest', etc.", verbose_name='Tags')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['full_name'],
            },
        ),
    ]
