# Generated by Django 4.2.26 on 2025-11-20 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='document_file',
            field=models.FileField(blank=True, null=True, upload_to='clients/docs/', verbose_name='Document File'),
        ),
        migrations.AddField(
            model_name='client',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='clients/photos/', verbose_name='Profile Picture'),
        ),
    ]
