# Generated by Django 4.2.27 on 2025-12-15 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_document_file_client_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='clients/docs/', verbose_name='Document File')),
                ('filename', models.CharField(help_text='Original filename of the uploaded document', max_length=255, verbose_name='Filename')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_attachments', to='clients.client', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Document Attachment',
                'verbose_name_plural': 'Document Attachments',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
