# Generated by Django 4.2.27 on 2025-12-15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_documentattachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='document_file',
        ),
        migrations.RemoveField(
            model_name='client',
            name='profile_picture',
        ),
    ]
