# Generated by Django 4.2.27 on 2025-12-15 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_remove_legacy_file_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='clients/photos/', verbose_name='Profile Picture'),
        ),
    ]
