# Generated by Django 4.2.27 on 2025-12-22 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_client_profile_picture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['full_name'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='documentattachment',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Anexo de Documento', 'verbose_name_plural': 'Anexos de Documentos'},
        ),
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='client',
            name='cpf',
            field=models.CharField(blank=True, help_text='Formato: XXX.XXX.XXX-XX', max_length=14, null=True, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='client',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='Nome Completo'),
        ),
        migrations.AlterField(
            model_name='client',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(help_text='Formato: +55 (XX) XXXXX-XXXX', max_length=20, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='client',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='clients/photos/', verbose_name='Foto de Perfil'),
        ),
        migrations.AlterField(
            model_name='client',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text="Lista de etiquetas como 'VIP', 'Hóspede Frequente', etc.", verbose_name='Etiquetas'),
        ),
        migrations.AlterField(
            model_name='documentattachment',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_attachments', to='clients.client', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='documentattachment',
            name='file',
            field=models.FileField(upload_to='clients/docs/', verbose_name='Arquivo de Documento'),
        ),
        migrations.AlterField(
            model_name='documentattachment',
            name='filename',
            field=models.CharField(help_text='Nome original do documento enviado', max_length=255, verbose_name='Nome do Arquivo'),
        ),
    ]
