# Generated by Django 4.2.27 on 2026-01-09 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_alter_client_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, help_text='Formato: +55 (XX) XXXXX-XXXX', max_length=20, null=True, verbose_name='Telefone'),
        ),
    ]
